baseURL = "https://reyortilla.com"
languageCode = "en"
languageLang = "en-us"

title = "My Hugo Blog"

[params]
  author = "Rey Ortilla"
  description = "This is my personal blog where I share what I learn."