baseURL = "https://reyortilla.com"
languageCode = "en-us"
languageLang = "en"
title = "Rey Ortilla"

[params]
  author = "Rey Ortilla"
  description = "This is my personal blog where I share what I'm learning."